### ISSUE TITLE
Addressing data gaps

### ISSUE THREAD

**Issue by ingomiller** [ianjonsen/aniMotum#34]
Hi,

in my data set of tracked marine non-air breathing animals, I have data gaps of up to ~60 days. Is there a way to set a maximum time between relocations (let's say 10 days) for interpolation? 

Cheers
Ingo

**Comment by ianjonsen** [comment]
There's no simple, general way to do this at the SSM-fitting/estimation stage, but you could write some code to automatically identify gaps > 10 d in your tracks and then split into sub-tracks, eg., where id's = track_1_a, track_1_b, ... and then use `fit_ssm()` as though each of these are unique individuals. This should generally work, provided the sub-tracks have a sufficient number of observations (typically > ~15-20) and duration (typically > ~10 `time.step`'s).
