### ISSUE TITLE
when none of the input locations from any of the tracks are on land, route_path fails

### ISSUE THREAD

**Issue by jganong** [ianjonsen/aniMotum#40]
When none of the locations from any of the tracks given to route_path are on land, route_path fails with the error message:
<simpleError in pathroutr::prt_visgraph(land_region, ...):barrier must be a simple feature collection with geometry type 'POLYGON' or 'MULTIPOLYGON>
If any of the paths have a point on land, this error does not occur.600

**To Reproduce**
library(data.table)
library(aniMotum)
toy_df=fread("id,date,lc,lon,lat
666,2003-06-27T12:08:11Z,1,-135.313,30.781
666,2003-06-29T08:47:31Z,A,-124.953,34.213
666,2003-07-01T03:23:14Z,B,-120.765,32.255
666,2003-07-01T08:03:51Z,B,-120.851,32.129
666,2003-07-01T11:21:58Z,A,-121.017,32.124
666,2003-07-01T13:02:27Z,B,-121.386,32.008
666,2003-07-02T01:29:54Z,A,-149.794,37.857
666,2003-07-02T04:44:40Z,A,-121.204,31.929
666,2003-07-02T05:03:28Z,B,-121.638,32.014
666,2003-07-02T06:00:16Z,0,-120.907,31.637
")  # all these points are not on land
fit_rw=fit_ssm(x=toy_df,model='rw',time.step=24)
fit_rw_reroute=route_path(fit_rw)
### results in the following error
Error in pathroutr::prt_visgraph(land_region, ...) :
  barrier must be a simple feature collection with geometry type 'POLYGON' or 'MULTIPOLYGON

**Expected behavior**
Instead of crashing, route_path() should return the locations unchanged, if there are no points on land.
This is easier for users of the data, rather than having to be aware of this issue and check two places (fit_rw and fit_rw_reroute)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - R in a terminal
 - R Version 4.2.2

**Additional context**
If just one track in a collection of tracks has no points on land, and other tracks do have points on land, this bug is not triggered.
I am going to put in a pull request shortly.

**Comment by ianjonsen** [comment]
PR accepted, associated updates complete & v1.1-04 will build in R-universe within next 18-24h.

Thanks James!
