### ISSUE TITLE
Package `foieGras` archived on CRAN and will be removed from the Tracking CTV

### ISSUE THREAD

**Issue by basille** [ianjonsen/aniMotum#43]
(**Note:** It is not clear to me whether `aniMotum` has simply replaced `foieGras`, so please don't hesitate to correct me here)

The package `foieGras` has been archived on CRAN for 60 days, and you are listed as the maintainer. This message is to let you know that your package is currently listed in the [Tracking CRAN Task View](https://cran.r-project.org/view=Tracking), but is flagged as "Archived", which means it will not get installed automatically with the CTV.

If the problem on your package persists for another 4 weeks, and the package is not reinstated on CRAN, it will also be removed from the Tracking CTV. Details of the situation can be found [here](https://github.com/cran-task-views/Tracking/issues/57).

It seems to us that the main issue was that a dependency (package `trip`) was no longer available on CRAN. However, `trip` has been reinstated on CRAN since then, and it is not clear to us if there are other blocking issues. Reinstating `foieGras` itself on CRAN might not be too complicated in the end.

Of course, if you are able to fix the problems of the package after it has been removed from the Tracking CTV, you can always ask for reinstatement in the Tracking CTV. In the meanwhile, please feel free to respond to this message or, better, to comment on the issue above.

Best,
For the Tracking CTV maintainers,
Mathieu Basille

**Comment by ianjonsen** [comment]
Following for others. AniMotum has fully replaced foieGras, although it is only available for download here and on R-universe. See information [here](https://github.com/ianjonsen/aniMotum#readme)  for install options
