### ISSUE TITLE
not sure if bug or system issue

### ISSUE THREAD

**Issue by KirstenFuller** [ianjonsen/aniMotum#50]
I am trying to run the following example code from the help file associated with the format_data function:

data(sese2_n)
head(sese2_n, 5)
d <- format_data(sese2_n, date = "time", coord = c("longitude","latitude"), tz = "America/Halifax")
fit <- fit_ssm(d, model = "crw", time.step = 24)

I got the following error:
fitting crw SSM to 2 tracks...
 pars:   1 1 0 0 -1.82873 0      Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  : 
  NA/NaN gradient evaluation

Error in updateCholesky(L, hessian.random) : 
  function 'sexp_as_cholmod_sparse' not provided by package 'Matrix'
Error in rep$pdHess : $ operator is invalid for atomic vectors

Anyone else experiencing this or can provide some insight? Is this an issue on my end or is this a bug with the code?

**Comment by ianjonsen** [comment]
That code runs without error on my system (Mac Arm64, R 4.3.2, aniMotum 1.2). First, I would ensure you're using the latest version of `aniMotum` (v 1.2). If you are on 1.2, the error you got suggests the issue arises when `TMB` tries to call functions within the `Matrix` pkg. , so I would try updating both of these pkg's if your versions are behind mine (`TMB` 1.9.6, `Matrix` 1.6-1.1).

Ian

**Comment by ianjonsen** [comment]
`aniMotum` has now been updated and built against the latest `TMB` version (1.9.10), so these `Matrix` errors should be fixed now

**Comment by ianjonsen** [comment]
The `aniMotum` rebuild against `TMB` 1.9.10 may solve the issue for some users, but this will be temporary. A sledgehammer solution is documented [here](https://github.com/glmmTMB/glmmTMB/issues/886#issuecomment-1461074619). `aniMotum` users need to replace the last step (5) with the following:

`install.packages("aniMotum", type = "source", repos = c("https://cloud.r-project.org",
                 "https://ianjonsen.r-universe.dev"))`
