### ISSUE TITLE
Error in strsplit(names(map), "_") : non-character argument

### ISSUE THREAD

**Issue by raorben** [ianjonsen/aniMotum#55]
**The bug**
I am trying to run the move persistence models on a bunch of albatross tracks. I have some slightly "messy" data that I am using to see how/where things don't work. I am able to fit the crw and then mpm separately on two tracks, but when I try to run the models together on the working track I get the following error: 
Error in strsplit(names(map), "_") : non-character argument

**To Reproduce**
Data file:
[MovePersist_exampledata.csv](https://github.com/ianjonsen/aniMotum/files/14166778/MovePersist_exampledata.csv)

> str(tracks_mp)
'data.frame':	6515 obs. of  5 variables:
 $ id  : chr  "MIAT19_3" "MIAT19_3" "MIAT19_3" "MIAT19_3" ...
 $ date: POSIXct, format: "2019-01-31 03:16:54" "2019-01-31 03:17:57" ...
 $ lc  : chr  "G" "G" "G" "G" ...
 $ lon : num  -177 -177 -177 -177 -177 ...
 $ lat : num  28.2 28.2 28.2 28.2 28.2 ...

CODE:
library(aniMotum)
library(dplyr) 
library(ggplot2) 
library(lubridate)

tracks_mp<-read.csv(MovePersist_exampledata.csv")
tracks_mp$date<-ymd_hms(tracks_mp$date)
str(tracks_mp)

wrap360 = function(lon) {lon360<-ifelse(lon<0,lon+360,lon);return(lon360)}

#quick visual of the three tracks
ggplot()+
  geom_path(data=tracks_mp,aes(x=wrap360(lon),y=lat,group=id, color=id))

##Slightly messy data for testing:
#MIAT19_3 - crosses 180 & has long colony time not trimmed from track <-mpm not converging
#MIAT23_103 - crosses 180 & has three trips + colony time in the middle
#MIAT23_65 - no 180 cross, 1 long trip, mpm converging when crw & mp are run separately, but fails when run together

fit_crw <- fit_ssm(tracks_mp,
               model = "crw",
               vmax = 30, 
               time.step=.16,
               control = ssm_control(verbose = 0)) #all converged ==true

fit_crw
summary(fit_crw)
plot(fit_crw, what = "fitted", type = 1, pages = 1)
plot(fit_crw, what = "predicted", type = 2, pages = 1) #all good!

fmp <- fit_mpm(fit_crw, 
               what = "predicted", 
               model = "mpm",
               control = mpm_control(verbose = 0))

#Error in nlminb(obj$par, ifelse(control$verbose == 1, myfn, obj$fn), obj$gr,  :NA/NaN gradient evaluation

#A tibble: 3 × 4
#id         mpm            converged model
#<chr>      <named list>   <lgl>     <chr>
#1 MIAT19_3   <try-errr [1]> FALSE     mpm  
#2 MIAT23_103 <mpm [8]>      TRUE      mpm  
#3 MIAT23_65  <mpm [8]>      TRUE      mpm     

#OK - so the tracks were a bit messy, so more data cleaning is clearly needed, but MIAT23_65 &  MIAT23_103 were OK for both models above. 

#all of the tracks fail when put in together
fit <- fit_ssm(tracks_mp, 
               vmax = 30, 
               model = "mp", 
               time.step = .16,
               control = ssm_control(verbose = 0))
#Error in strsplit(names(map), "_") : non-character argument

#but so does MIAT23_65. Same thing with MIAT23_103
tracks_mp_65<-tracks_mp%>%filter(id=="MIAT23_65")
str(tracks_mp_65)
fit <- fit_ssm(tracks_mp_65, 
               vmax = 30, 
               model = "mp", 
               time.step = .16,
               control = ssm_control(verbose = 0))
#Error in strsplit(names(map), "_") : non-character argument

**Desktop**
 - OS: MacOS 12.7.2
 - RStudio: Version 2023.06.1+524 (2023.06.1+524)
 - R Version: #R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
 - AniMomentum: 1.2-02
 - TMB 1.9.10

**Comment by ianjonsen** [comment]
Hi Rachel,

Thanks for pointing out this issue. The 'mp' SSM is not being parameterized correctly when input data is GPS, this causes the fairly uninformative error you are getting. I've pushed an update (v 1.2-03) that resolves the problem. 

Ian
