### ISSUE TITLE
osar function not finishing the run

### ISSUE THREAD

**Issue by francisvolh** [ianjonsen/aniMotum#56]
Hello, I attended a seminar given today by @jamesgrecian and I tried the code after the seminar because I had issues with installing TBM it seems, and I was only able to fit an ssm after the seminar. 

I have followed the tutorial here https://github.com/eco4cast/Statistical-Methods-Seminar-Series/tree/main/grecian-aniMotum
  
but I get stuck at
`res <- aniMotum::osar(fit)` 
using the harp seal dataset of 3 individuals. 

My last attempt has been running for 2 hours and never stopped or had an error. The fit model from the fit_ssm() comes from the same dataset and it runs in 30 seconds. I do not know if this is bug in itself of just performance issues of my computer.

My computer specs here:
Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

And my Rversion
               _                                
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          3.1                              
year           2023                             
month          06                               
day            16                               
svn rev        84548                            
language       R                                
version.string R version 4.3.1 (2023-06-16 ucrt)
nickname       Beagle Scouts   

I would like to run the code on my own data, but I wonder what the issue is with this function. Thanks!

**Comment by jamesgrecian** [comment]
Hi @francisvolh thanks for attending the webinar. As I mentioned during the session the `aniMotum::osar` function is computationally very demanding. Previously I have left my computer to run overnight before the function returns a result. Given the function hasn't crashed or returned an error, I would suggest giving it some more time.

**Comment by francisvolh** [comment]
Thanks @jamesgrecian ! I loved the webinar and the package seems a lot more powerful since it evolved from foiegras. I need to fill some gaps in a few GPS tracks, so I was hoping to use aniMotum. The tutorial said it should take 10-20 times longer than fitting a ssm, which was 30 seconds, so I assumed only 10 minutes or maybe 20 or so. But I guess it was a lot longer. I wonder if how it would behave with my data. Thanks again for the response! and I will come back to you if after 10-20 hours nothing happened! Cheers!
