### ISSUE TITLE
manual download binary version animotum

### ISSUE THREAD

**Issue by WhitneyMax** [ianjonsen/aniMotum#65]
**Describe the bug**
link to download binary version of aniMotum doesn't work. States R-universe error. 

**To Reproduce**
link from GitHub: 
https://ianjonsen.r-universe.dev/ui#package:aniMotum 

**Expected behavior**
Just want to download binary version of aniMotum for Mac. I have failed multiple times at loading the package into R other ways. 

**Screenshots**
<img width="720" alt="Screenshot 2024-06-04 at 11 58 45 AM" src="https://github.com/ianjonsen/aniMotum/assets/171713517/5971aec8-39b2-40bb-8dee-aff334ea684c">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - RStudio
 - R Version 4.4.0

**Additional context**

**Comment by ianjonsen** [comment]
the url changed, you can find the r-universe binaries at [https://ianjonsen.r-universe.dev/aniMotum](https://ianjonsen.r-universe.dev/aniMotum)
