### ISSUE TITLE
fit ssm

### ISSUE THREAD

**Issue by joanna-br** [ianjonsen/aniMotum#69]
Hello, I'm trying to fit an SSM of whale shark data for my master's project. This is the code I have written which follows the examples: 
fit <- fit_ssm(WSformated, 
               vmax= 3, 
               model = "mp", 
               time.step = 24, 
               control = ssm_control(verbose = 0))

I get an error: Error in if (p.GL > 0.75) { : missing value where TRUE/FALSE needed

Could you please help me resolve this, I'm not sure what this is due to. I've also checked for NA values.

Thank you, 

Joanna Branstetter
MSci Marine Biology 
University of Southampton
jrb1u21@soton.ac.uk

**Comment by jamesgrecian** [comment]
Hi @joanna-br could you have a look at #52 and check whether the info there helps you
